# Generated by Django 3.0.3 on 2023-11-24 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='to_validate_date',
            field=models.TextField(default=datetime.datetime(2023, 11, 24, 16, 55, 23, 731190)),
        ),
        migrations.AlterModelTable(
            name='proxy',
            table='proxy',
        ),
    ]
