# Generated by Django 3.0.3 on 2023-11-24 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_auto_20231124_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='to_validate_date',
            field=models.TextField(default=datetime.datetime(2023, 11, 24, 16, 56, 43, 946399)),
        ),
    ]
